### ISSUE TITLE
how to found remote code?

### ISSUE THREAD

**Issue by coverdh** [Zzm317/homebridge-mi-ir-remote#1]
"type": "Projector",
            "ip": "192.168.31.xx",
            "token": "xxxxxxxx",
            "Name": "IR Projector",
            "interval": 1,
            "data": {
                "on" : "xxxxxxxxxxxxx",
                "off": "xxxxxxxxxxxxx"
            }
xxxxxx?

**Comment by Zzm317** [comment]
press irLearn
make sure your mi remote can receive the signal of your remote  
press the button on your remote
see the log on console
copy the code to config

**Comment by Zzm317** [comment]
Don't forget to enable irLearn and edit ip and token in learn config

**Comment by coverdh** [comment]
get it，thanks
