### ISSUE TITLE
After 'miio' updated, it's not work.

### ISSUE THREAD

**Issue by Km81** [Zzm317/homebridge-mi-ir-remote#12]
After 'miio' updated, it's not work with follwoing message.

TypeError: miio.Device is not a constructor
~~

Please check and update it.

**Comment by Zzm317** [comment]
The author changed miio.Device to miio.device

**Comment by sunwoo0413** [comment]
It solved but I have another error
TypeError: that.device.call is not a function

**Comment by Zzm317** [comment]
yep
the author rewrite the promise
what you can do now is to downgrade your miio or wait for the upgrade

**Comment by Zzm317** [comment]
https://github.com/Zzm317/homebridge-mi-ir-remote/commit/e45636161e9d61fc3ff0b4c595ac29707489fa19

updated the support for miio.device

**Comment by Zzm317** [comment]
I suggest you to downgrade your miio version
the new version of miio is not suitable for this plugin

**Comment by Km81** [comment]
First of all, thanks for your rapid support.

After install 'npm install -g miio@0.14.1', the problem is solved.

Thanks for your advice again.

For other users, please refer to below install setting.

As is
npm install -g miio homebridge-mi-ir-remote

To be
npm install -g miio@0.14.1
npm install -g homebridge-mi-ir-remote

**Comment by neshala** [comment]
Even after doing
`npm install -g miio@0.14.1`

I can't get token, simply showing ???. I have also tried --sync, but nothing.

```
I ma getting this:
Device ID: 45142997
Model info: Unknown
Address: 192.168.0.29
Token: ???
Support: Unknown
```

with this command: 
`miio --discover --sync`

Any idea?
