### ISSUE TITLE
Miio updated and not work

### ISSUE THREAD

**Issue by sunwoo0413** [Zzm317/homebridge-mi-ir-remote#13]
After 'miio' updated, it's not work with follwoing message.

TypeError: miio.Device is not a constructor
I solved this error But I have another error
TypeError: that.device.call is not a function
Please solve it

**Comment by Zzm317** [comment]
Can you learn to read the issues first before you open the fuc*ing issue?

https://github.com/Zzm317/homebridge-mi-ir-remote/issues/12

**Comment by sunwoo0413** [comment]
fucking shit I can't find this contents of issue.
