### ISSUE TITLE
Use for chuangmi_ir issue

### ISSUE THREAD

**Issue by hzx1987227** [Zzm317/homebridge-mi-ir-remote#16]
Hello,

I use your homebridge-mi-ir-remote for chuangmi_ir.(AirConditioner )

When i changed the temperature from iphone just nothing happened...

Here is the log:

hassbian homebridge[2684]: [1/29/2018, 10:56:46 PM] [ChuangmiIRPlatform] [IR AC]AirConditioner: Unready

hassbian homebridge[2684]: [1/29/2018, 10:53:07 PM] [ChuangmiIRPlatform] [irLearn] Learn Started
hassbian homebridge[2684]: [1/29/2018, 10:53:07 PM] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready

The token and IR setting is worked for https://github.com/syssi/chuangmi_ir   (HA 0.62)

Could you please give me some advice  it will be very helpful.

Thank you!

**Comment by Zzm317** [comment]
Unready means the new version of miio failed to communicate with your device or your device is offline
Please use miio@0.14.1 the new version of miio is not suitable for my plugin

**Comment by hzx1987227** [comment]
Oh.. i see.

Thanks for your reply.
