### ISSUE TITLE
Learn Failed, Status Unready

### ISSUE THREAD

**Issue by JuvenRui** [Zzm317/homebridge-mi-ir-remote#17]
config.json:
{
        "platform": "ChuangmiIRPlatform",
        "hidelearn": false,
        "learnconfig": {
            "ip": " 192.168.1.248",
            "token": "3d28392fcb34205174a1fca9257801f2"
        },
        "deviceCfgs": [{}]
}

重启homebridge后，点击Milearn开关，无法进入学习模式，日志显示：
Mar 10 20:47:28 raspberrypi homebridge[5510]: [2018-3-10 20:47:28] [ChuangmiIRPlatform] [irLearn] Learn Started
Mar 10 20:47:28 raspberrypi homebridge[5510]: [2018-3-10 20:47:28] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready
Mar 10 20:47:30 raspberrypi homebridge[5510]: [2018-3-10 20:47:30] [ChuangmiIRPlatform] [irLearn] Learn Started
Mar 10 20:47:30 raspberrypi homebridge[5510]: [2018-3-10 20:47:30] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready

**Comment by Zzm317** [comment]
请使用miio@0.14.1
