### ISSUE TITLE
How to config the "data" entry in config.json

### ISSUE THREAD

**Issue by AnyOfYou** [Zzm317/homebridge-mi-ir-remote#2]
Take AirConditioner as a example. The configuration in README.md shown as below:

`
"data": {
    "Cool":{
        "30" : "xxx",
        "25" : "xxx",
        "20" : "xxx",
        "16" : "xxx"
    },
    "Heat":{
        "30" : "xxx",
        "25" : "xxx",
        "20" : "xxx",
        "16" : "xxx"
    },
    "off" : "xxxx"
}
`

Many "xxx" as placeholder, so how do we get the actual value of each command?

**Comment by AnyOfYou** [comment]
OK, I got it. U should active MiLearn from Home app then try to learn each command manual.
At the meantime, you are supposed to see the command string come out in the HomeBridge console.
Just like:
`[10/27/2017, 2:39:35 AM] [ChuangmiIRPlatform] [MiIRRemote][irLearn]Learned Code: Z6WDAC8CAAAIBQAAAggAALsiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAAAAAAAQABAQAAAAAAAAAAAAABAQAAAAEAAAABAAAAAQEAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEBAQAAA=
`
Just grab the string then fill it to config file, everything should be working

**Comment by Zzm317** [comment]
that’s right
Sorry for the incomplete readme file
I will improve it and add more functions later
