### ISSUE TITLE
Question on air conditioner control

### ISSUE THREAD

**Issue by niccolospa** [Zzm317/homebridge-mi-ir-remote#23]
Hello,
I would like to ask: if I have an air conditioner that has the same hex code for on/off, how can I configure for temperature? 
At the moment I can do that the temperature slider changes temperature only if the conditioner is on. Because if I configure the hex codes by doing the learning this way: "setting the temperature first on the remote and then pressing the power button", the problem is that whenever I change temperature from home the conditioner switches on and off.

**Comment by Zzm317** [comment]
Just write the same
or write an auto mode code instead
