### ISSUE TITLE
Question regarding how to configure the plugin

### ISSUE THREAD

**Issue by maisun** [Zzm317/homebridge-mi-ir-remote#3]
How to find the values for "xxxxxxx"? I have configured some scenes which send several commands in one go, is it possible to enable/disable the scene directly?
{
            "type": "Projector",
            "ip": "192.168.31.xx",
            "token": "xxxxxxxx",
            "Name": "IR Projector",
            "interval": 1,
            "data": {
                "on" : "xxxxxxxxxxxxx",
                "off": "xxxxxxxxxxxxx"
}

**Comment by Zzm317** [comment]
See https://github.com/Zzm317/homebridge-mi-ir-remote/issues/2

**Comment by maisun** [comment]
Thank you! But what is MiLearn?
And would it be possible to support sequence of commands (like an action which turns on multiple devices)?

**Comment by Zzm317** [comment]
MiLearn is irLearn
the support for multiple commands is still in progress

**Comment by maisun** [comment]
Cool! Thx!

**Comment by acc-ua** [comment]
Plugin works great, but I had to specify the "Auto" configuration section (in addition to Cool or Heat sections) to make Siri able to turn air conditioner on.  Without it, it just turn it on and then off immediately.

Thanks for your work.

**Comment by Zzm317** [comment]
yep, siri use auto mode instead of choose the mode by itself. So you have to specify Auto mode. If this plugin has any other problems, just make an issue to let me know!

**Comment by acc-ua** [comment]
Just a quick question, if I need to control two devices with a single switch, should I just put two hex codes (concatenated) into "on" : "xxxxxxxxxxxxx"  value?

For example, if I want to turn on/off TV and IPTV box  both?

**Comment by Zzm317** [comment]
Not supported yet. you can add a scene instead.
This function will be added later

**Comment by Zzm317** [comment]
@acc-ua I have updated the plugin and added custom function.
Just try if it can meet your requirements

**Comment by acc-ua** [comment]
Cool, thanks a lot.  Will check it today.

**Comment by acc-ua** [comment]
Everything works really good. thanks again
