### ISSUE TITLE
Could we use codes from sites like these?

### ISSUE THREAD

**Issue by nimbling** [Zzm317/homebridge-mi-ir-remote#5]
I'm trying to control a device of which I never owned the remote.
I did find some models that might share the IR instruction set, at sites like this one: [http://irdb.tk/codes/](http://irdb.tk/codes/). Are any of the code formats listed there (Pronto hex, UEI Hex or RAW (mostly empty there...)) usable?

Thanks so much for making this by the way!

**Comment by Zzm317** [comment]
The code get from the remote has been encoded by the ir remote.
So the hex code cann't be used before it's encoded.
You can try to get a device that can send hex code and than use the ir remote to learn the code.

**Comment by Zzm317** [comment]
But I don't know if ir remote can recognize the hex code or not.
So you can try to send the hex code to see if it works.

**Comment by nimbling** [comment]
Thanks!
Yes, I was kind of stuck at the "don't have the remote" part :)

What kind of encoding is used?
Do you think I could convert the codes found on those websites to try them out using mi-ir-remote?

**Comment by Zzm317** [comment]
If I know what kind of encoding it uses
I will let it support hex code.......

**Comment by nimbling** [comment]
that would be super cool! :)

**Comment by nimbling** [comment]
Would you know how I could find out what encoding a remote or device uses?

On the irdb.tk website they're sorted by "Pronto hex", "UEI Hex" and RAW encodings, is there another type I'm missing?

**Comment by nimbling** [comment]
For instance, for my pioneer AV Receiver, this would switch to CD:

Remote control code: A54C
`0000 0068 0000 0022 0168 00b4 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0016 0016 0043 0016 0043 0016 0016 0016 0016 0016 0043 0016 0016 0016 0043 0016 0043 0016 0016 0016 0016 0016 0043 0016 0043 0016 0016 0016 0043 0016 06d9`

Could I just use codes like that?

**Comment by Zzm317** [comment]
MomentarySwitch only supports to send one command when you press the switch
