### ISSUE TITLE
Can not learn commands.

### ISSUE THREAD

**Issue by s-triant** [Zzm317/homebridge-mi-ir-remote#6]
When I activate MiLearn in the Home app, I get the following in the console:
> [2017-12-26 19:17:41] [ChuangmiIRPlatform] [MiIRRemote][irLearn] Learn Started
> [2017-12-26 19:17:43] [ChuangmiIRPlatform] [MiIRRemote][irLearn][ERROR] Error: Error: Method `miIO.ir_read` is not supported
> (node:10319) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: callback is not defined
> (node:10319) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [2017-12-26 19:17:44] [ChuangmiIRPlatform] [MiIRRemote][irLearn][ERROR] Error: Error: Method `miIO.ir_read` is not supported
> (node:10319) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: callback is not defined
> [2017-12-26 19:17:45] [ChuangmiIRPlatform] [MiIRRemote][irLearn][ERROR] Error: Error: Method `miIO.ir_read` is not supported
> (node:10319) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: callback is not defined
> [2017-12-26 19:17:46] [ChuangmiIRPlatform] [MiIRRemote][irLearn] Learn Stopped

**Comment by Zzm317** [comment]
please check your ip and token
this error usually caused by ip or token error

**Comment by s-triant** [comment]
Yes, that was the case. I had accidentally written ip and token from another device. After correction everything works fine. Thank you!
