### ISSUE TITLE
How to add multiple 小米万能遥控

### ISSUE THREAD

**Issue by Fox123456** [Zzm317/homebridge-mi-ir-remote#7]
How to add multiple 小米万能遥控?

**Comment by Fox123456** [comment]
多个小米万能遥控器如何加到 homebridge

**Comment by Zzm317** [comment]
用ip和token区分

**Comment by Fox123456** [comment]
第二個的小米万能遥控器 platform name 要区分嗎? 還是跟第一個的名字就可以?
"platform": "ChuangmiIRPlatform"

**Comment by Zzm317** [comment]
请仔细学习homebridge的config再来问这种问题谢谢

**Comment by Fox123456** [comment]
Already read thru but cannot find the answer. Please let me know.
