### ISSUE TITLE
Timeout when try to learn 

### ISSUE THREAD

**Issue by xell29** [Zzm317/homebridge-mi-ir-remote#9]
Hello Zzm317,
I have installed node 9.4.0, latest firmware on Xiaomi IR device, latest miIO and when I try to run learn I get nothing... In logs first off all I get error on 120 string of MiRemoteirLearn.js device file (callbak). I have commented this line and change other log from debug to info after that I did start recieve messages about timeout...
I have success test:
miio --discover 
and get all info, also success:
miio --update MY_DEVICE_ID --token MY_DEVICE_TOKEN
maybe problem in used commands: "miIO.ir_learn" or "miIO.ir_read" ? Probably it changed in latest firmware?
Help me please
Thanks

**Comment by Zzm317** [comment]
check your ip and token
Call to device timeout is usually caused by wrong ip or token

**Comment by xell29** [comment]
result from miio --discover is :
.....
.....
.....
Token: MY_DEVICE_TOKEN via auto-token

but what means 'via auto-token' maybe this auto-token wrong?
Probably exists different way to get correct device token?

**Comment by xell29** [comment]
You are right! I made mistake in IP for learn device! Sorry for the trouble. All works fine, thanks!
